import SchemaBuilder from '@pothos/core'
import RelayPlugin from '@pothos/plugin-relay'
import PrismaPlugin from '@pothos/plugin-prisma'
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore – generated by prisma generator
import type PrismaTypes from '../../node_modules/@pothos/plugin-prisma/generated'
import { prisma } from '@/lib/prisma'
import { Prisma } from '@prisma/client'
import type { Plan, JobType, PostingStatus } from '@prisma/client'

export const builder = new SchemaBuilder<{
  PrismaTypes: PrismaTypes
  Context: {
    userId: string | null
  }
  Scalars: {
    DateTime: { Input: Date; Output: Date }
    JSON: { Input: unknown; Output: unknown }
  }
}>({
  plugins: [RelayPlugin, PrismaPlugin],
  relay: {
    clientMutationId: 'omit',
    cursorType: 'String',
  },
  prisma: {
    client: (_ctx: { userId: string | null }) => prisma,
    dmmf: Prisma.dmmf,
    exposeDescriptions: false,
    filterConnectionTotalCount: true,
  },
})

// Scalars
builder.scalarType('DateTime', {
  serialize: (value) => (value instanceof Date ? value.toISOString() : String(value)),
  parseValue: (value) => new Date(value as string),
})

builder.scalarType('JSON', {
  serialize: (value) => value,
  parseValue: (value) => value,
})

// Enums
const PlanEnum = builder.enumType('Plan', {
  values: ['FREE', 'PRO', 'TEAM'] as const,
})

const JobTypeEnum = builder.enumType('JobType', {
  values: ['FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP'] as const,
})

const PostingStatusEnum = builder.enumType('PostingStatus', {
  values: ['DRAFT', 'PUBLISHED', 'PAUSED', 'EXPIRED'] as const,
})

// Types
const UserType = builder.prismaObject('User', {
  fields: (t) => ({
    id: t.exposeID('id'),
    email: t.exposeString('email'),
    name: t.exposeString('name', { nullable: true }),
    image: t.exposeString('image', { nullable: true }),
    plan: t.expose('plan', { type: PlanEnum }),
    createdAt: t.expose('createdAt', { type: 'DateTime' }),
    postings: t.relation('postings'),
  }),
})

const JobPostingType = builder.prismaObject('JobPosting', {
  fields: (t) => ({
    id: t.exposeID('id'),
    title: t.exposeString('title'),
    company: t.exposeString('company'),
    location: t.exposeString('location'),
    jobType: t.expose('jobType', { type: JobTypeEnum }),
    category: t.exposeString('category'),
    salaryMin: t.exposeInt('salaryMin', { nullable: true }),
    salaryMax: t.exposeInt('salaryMax', { nullable: true }),
    currency: t.exposeString('currency'),
    description: t.exposeString('description'),
    requirements: t.exposeStringList('requirements'),
    benefits: t.exposeStringList('benefits'),
    status: t.expose('status', { type: PostingStatusEnum }),
    aiScore: t.exposeInt('aiScore', { nullable: true }),
    aiSuggestions: t.expose('aiSuggestions', { type: 'JSON', nullable: true }),
    views: t.exposeInt('views'),
    applications: t.exposeInt('applications'),
    publishedAt: t.expose('publishedAt', { type: 'DateTime', nullable: true }),
    expiresAt: t.expose('expiresAt', { type: 'DateTime', nullable: true }),
    createdAt: t.expose('createdAt', { type: 'DateTime' }),
    updatedAt: t.expose('updatedAt', { type: 'DateTime' }),
    userId: t.exposeString('userId'),
    user: t.relation('user'),
  }),
})

// Input types
const CreatePostingInput = builder.inputType('CreatePostingInput', {
  fields: (t) => ({
    title: t.string({ required: true }),
    company: t.string({ required: true }),
    location: t.string({ required: true }),
    jobType: t.field({ type: JobTypeEnum, required: false }),
    category: t.string({ required: false }),
    salaryMin: t.int({ required: false }),
    salaryMax: t.int({ required: false }),
    currency: t.string({ required: false }),
    description: t.string({ required: false }),
    requirements: t.stringList({ required: false }),
    benefits: t.stringList({ required: false }),
  }),
})

const UpdatePostingInput = builder.inputType('UpdatePostingInput', {
  fields: (t) => ({
    title: t.string({ required: false }),
    company: t.string({ required: false }),
    location: t.string({ required: false }),
    jobType: t.field({ type: JobTypeEnum, required: false }),
    category: t.string({ required: false }),
    salaryMin: t.int({ required: false }),
    salaryMax: t.int({ required: false }),
    currency: t.string({ required: false }),
    description: t.string({ required: false }),
    requirements: t.stringList({ required: false }),
    benefits: t.stringList({ required: false }),
    status: t.field({ type: PostingStatusEnum, required: false }),
    expiresAt: t.field({ type: 'DateTime', required: false }),
  }),
})

// Query
builder.queryType({
  fields: (t) => ({
    me: t.prismaField({
      type: 'User',
      nullable: true,
      resolve: async (query, _root, _args, ctx) => {
        if (!ctx.userId) return null
        return prisma.user.findUnique({
          ...query,
          where: { id: ctx.userId },
        })
      },
    }),

    posting: t.prismaField({
      type: 'JobPosting',
      nullable: true,
      args: {
        id: t.arg.string({ required: true }),
      },
      resolve: async (query, _root, args, ctx) => {
        const posting = await prisma.jobPosting.findUnique({
          ...query,
          where: { id: args.id },
        })
        // Public postings are viewable without auth
        if (!posting) return null
        if (posting.status !== 'PUBLISHED' && posting.userId !== ctx.userId) return null
        return posting
      },
    }),

    postings: t.prismaConnection({
      type: 'JobPosting',
      cursor: 'id',
      args: {
        status: t.arg({ type: PostingStatusEnum, required: false }),
      },
      resolve: async (query, _root, args, ctx) => {
        if (!ctx.userId) return []
        return prisma.jobPosting.findMany({
          ...query,
          where: {
            userId: ctx.userId,
            ...(args.status ? { status: args.status as PostingStatus } : {}),
          },
          orderBy: { createdAt: 'desc' },
        })
      },
      totalCount: async (_root, args, ctx) => {
        if (!ctx.userId) return 0
        return prisma.jobPosting.count({
          where: {
            userId: ctx.userId,
            ...(args.status ? { status: args.status as PostingStatus } : {}),
          },
        })
      },
    }),
  }),
})

// Mutation
builder.mutationType({
  fields: (t) => ({
    createPosting: t.prismaField({
      type: 'JobPosting',
      args: {
        input: t.arg({ type: CreatePostingInput, required: true }),
      },
      resolve: async (query, _root, args, ctx) => {
        if (!ctx.userId) throw new Error('Unauthorized')
        return prisma.jobPosting.create({
          ...query,
          data: {
            userId: ctx.userId,
            title: args.input.title,
            company: args.input.company,
            location: args.input.location,
            jobType: (args.input.jobType as JobType | null | undefined) ?? 'FULL_TIME',
            category: args.input.category ?? 'Engineering',
            salaryMin: args.input.salaryMin ?? null,
            salaryMax: args.input.salaryMax ?? null,
            currency: args.input.currency ?? 'KRW',
            description: args.input.description ?? '',
            requirements: args.input.requirements ?? [],
            benefits: args.input.benefits ?? [],
          },
        })
      },
    }),

    updatePosting: t.prismaField({
      type: 'JobPosting',
      args: {
        id: t.arg.string({ required: true }),
        input: t.arg({ type: UpdatePostingInput, required: true }),
      },
      resolve: async (query, _root, args, ctx) => {
        if (!ctx.userId) throw new Error('Unauthorized')
        const posting = await prisma.jobPosting.findUnique({ where: { id: args.id } })
        if (!posting || posting.userId !== ctx.userId) throw new Error('Not found')
        return prisma.jobPosting.update({
          ...query,
          where: { id: args.id },
          data: {
            ...(args.input.title != null ? { title: args.input.title } : {}),
            ...(args.input.company != null ? { company: args.input.company } : {}),
            ...(args.input.location != null ? { location: args.input.location } : {}),
            ...(args.input.jobType != null ? { jobType: args.input.jobType as JobType } : {}),
            ...(args.input.category != null ? { category: args.input.category } : {}),
            ...(args.input.salaryMin !== undefined ? { salaryMin: args.input.salaryMin } : {}),
            ...(args.input.salaryMax !== undefined ? { salaryMax: args.input.salaryMax } : {}),
            ...(args.input.currency != null ? { currency: args.input.currency } : {}),
            ...(args.input.description != null ? { description: args.input.description } : {}),
            ...(args.input.requirements != null ? { requirements: args.input.requirements } : {}),
            ...(args.input.benefits != null ? { benefits: args.input.benefits } : {}),
            ...(args.input.status != null ? { status: args.input.status as PostingStatus } : {}),
            ...(args.input.expiresAt !== undefined ? { expiresAt: args.input.expiresAt } : {}),
          },
        })
      },
    }),

    publishPosting: t.prismaField({
      type: 'JobPosting',
      args: {
        id: t.arg.string({ required: true }),
      },
      resolve: async (query, _root, args, ctx) => {
        if (!ctx.userId) throw new Error('Unauthorized')
        const posting = await prisma.jobPosting.findUnique({ where: { id: args.id } })
        if (!posting || posting.userId !== ctx.userId) throw new Error('Not found')
        return prisma.jobPosting.update({
          ...query,
          where: { id: args.id },
          data: { status: 'PUBLISHED', publishedAt: new Date() },
        })
      },
    }),

    deletePosting: t.boolean({
      args: {
        id: t.arg.string({ required: true }),
      },
      resolve: async (_root, args, ctx) => {
        if (!ctx.userId) throw new Error('Unauthorized')
        const posting = await prisma.jobPosting.findUnique({ where: { id: args.id } })
        if (!posting || posting.userId !== ctx.userId) throw new Error('Not found')
        await prisma.jobPosting.delete({ where: { id: args.id } })
        return true
      },
    }),

    updatePostingScore: t.prismaField({
      type: 'JobPosting',
      args: {
        id: t.arg.string({ required: true }),
        score: t.arg.int({ required: true }),
        suggestions: t.arg({ type: 'JSON', required: false }),
      },
      resolve: async (query, _root, args, ctx) => {
        if (!ctx.userId) throw new Error('Unauthorized')
        const posting = await prisma.jobPosting.findUnique({ where: { id: args.id } })
        if (!posting || posting.userId !== ctx.userId) throw new Error('Not found')
        return prisma.jobPosting.update({
          ...query,
          where: { id: args.id },
          data: {
            aiScore: args.score,
            aiSuggestions: args.suggestions ?? undefined,
          },
        })
      },
    }),
  }),
})

export const schema = builder.toSchema()
